# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mtribes < Formula
  desc "A CLI to help automate app integration with mtribes."
  homepage "https://mtribes.com"
  version "0.27.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mtribes/cli/releases/download/v0.27.0/mtribes_Darwin_x86_64.tar.gz"
      sha256 "93e63f343195a435fa5274dd8aeeacffa480fd54ae8a1e24314c3c5be8e25d97"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mtribes/cli/releases/download/v0.27.0/mtribes_Linux_x86_64.tar.gz"
      sha256 "12ff991c90b77d5eb89832aa9ede378f5c538e8bd9b59a4545da58e3fba5574f"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mtribes/cli/releases/download/v0.27.0/mtribes_Linux_armv6.tar.gz"
      sha256 "ebc949a6cc6e4e59fb62e0fc57177083cea81fdfed1a07b0ebc69da963520b98"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mtribes/cli/releases/download/v0.27.0/mtribes_Linux_arm64.tar.gz"
      sha256 "ef7729a758184ed5a0d7671b7345b561afe29ac03ce3823c56a8cc927fb2f187"
    end
  end

  def install
    bin.install "mtribes"
  end

  test do
    system "#{bin}/mtribes --version"
  end
end
