# This file was generated by GoReleaser. DO NOT EDIT.
class Mtribes < Formula
  desc "A CLI to help automate app integration with mtribes."
  homepage "https://mtribes.com"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://mtribes-cli.s3-us-west-2.amazonaws.com/release/v0.0.1/mtribes_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "a2a43222bf96b16158c317fc6d01b3203cc87dcdb5deed0483ca1ea67068a0db"
  elsif OS.linux?
    url "https://mtribes-cli.s3-us-west-2.amazonaws.com/release/v0.0.1/mtribes_0.0.1_Linux_x86_64.tar.gz"
    sha256 "0c542d535cbda094fdc51a46050c614ea6c16208191269a91cc8a2f95b4fe18b"
  end

  def install
    bin.install "mtribes"
  end

  test do
    system "#{bin}/mtribes --version"
  end
end
